# Generated by Django 4.0.1 on 2022-01-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0002_alter_film_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodatkoweInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Inne'), (2, 'Komedia'), (4, 'Drama'), (3, 'Sci-Fi')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.dodatkoweinfo'),
        ),
    ]
